const statesData = {
    maharashtra: {
        name: 'Maharashtra',
        districts: [
            'Ahmednagar',
            'Akola',
            'Amravati',
            'Aurangabad',
            'Beed',
            'Bhandara',
            'Buldhana',
            'Chandrapur',
            'Dhule',
            'Gadchiroli',
            'Gondia',
            'Hingoli',
            'Jalgaon',
            'Jalna',
            'Kolhapur',
            'Latur',
            'Mumbai City',
            'Mumbai Suburban',
            'Nagpur',
            'Nanded',
            'Nandurbar',
            'Nashik',
            'Osmanabad',
            'Palghar',
            'Parbhani',
            'Pune',
            'Raigad',
            'Ratnagiri',
            'Sangli',
            'Satara',
            'Sindhudurg',
            'Solapur',
            'Thane',
            'Wardha',
            'Washim',
            'Yavatmal'
        ],
    },
    karnataka: {
        name: 'Karnataka',
        districts: [
            'Bagalkot',
            'Ballari',
            'Belagavi',
            'Bengaluru Rural',
            'Bengaluru Urban',
            'Bidar',
            'Chamarajanagar',
            'Chikkaballapur',
            'Chikkamagaluru',
            'Chitradurga',
            'Dakshina Kannada',
            'Davanagere',
            'Dharwad',
            'Gadag',
            'Hassan',
            'Haveri',
            'Kalaburagi',
            'Kodagu',
            'Kolar',
            'Koppal',
            'Mandya',
            'Mysuru',
            'Raichur',
            'Ramanagara',
            'Shivamogga',
            'Tumakuru',
            'Udupi',
            'Uttara Kannada',
            'Vijayapura',
            'Yadgir'
        ],
    },
    
};

export default statesData;